// Shared FAQ question/answer data — single source for the FAQ page's
// FAQPage JSON-LD block (src/app/faq/page.tsx) and the /md/faq Markdown
// mirror (src/app/md/[slug]/route.ts). Keeps both in sync automatically.
//
// This does not replace the FAQ page's themed, narrative visible sections
// (those stay hand-authored in page.tsx for editorial structure) — it's the
// flat, structured version already needed for schema.org markup.

export type FaqItem = { question: string; answer: string };

export const FAQ_ITEMS: FaqItem[] = [
  { question: "Who runs Dreamglade?", answer: "Dreamglade was founded by Stacy Povey in 2013 and later came under the care of Wade Bucher and Clarisa Gutierrez in 2023. Paul reviews every application personally." },
  { question: "How many guests are at a retreat?", answer: "A maximum of ten guests per retreat. We do not run larger groups." },
  { question: "Where is Dreamglade located?", answer: "Dreamglade is near Moralillo, under an hour's drive from Iquitos in the Peruvian Amazon. The property is 25 hectares of rainforest lakeside." },
  { question: "Is Dreamglade good for first-time ayahuasca guests?", answer: "Yes. Many guests come to Dreamglade for their first ayahuasca experience. The small group of no more than ten, the traditional Shipibo-led ceremonies, and Paul's personal screening and preparation are designed to make a first time feel safe and well supported." },
  { question: "Is airport pickup included?", answer: "No. Airport pickup when you fly into Iquitos is not included. Uber is available in Iquitos, but it is smart to bring cash in soles in case Uber is not working or a driver asks for cash. Motor taxis from the airport to hotels in Iquitos usually cost about 30–70 soles. You then meet us at the designated city meeting point in Iquitos on your first retreat day." },
  { question: "How do I get to Dreamglade from Iquitos?", answer: "You make your own way to Iquitos, and we take it from there. After your application is confirmed, we meet you at a designated city meeting point in Iquitos and drive you to the property by 4x4, under an hour from the city. There is no public route to the centre — arrival transport is arranged by us and included." },
  { question: "What are the accommodations like?", answer: "Guests sleep in private, two-person, or communal thatched tambos, all raised off the ground, with mosquito-screened sleeping and most overlooking the lake or jungle. Comfort is simple and clean rather than luxury: a real bed, quiet, and the forest right outside. Meals and gathering happen at the communal big house." },
  { question: "Who leads the ceremonies?", answer: "Ceremonies are led by Maestra Dominga and Maestro Raúl in the traditional Shipibo ceremonial lineage. A support team is in the room throughout." },
  { question: "How many ceremonies will I have, and when?", answer: "Ceremonies are held on Monday, Wednesday, and Friday nights. The minimum stay of five nights includes three ceremonies. A Friday start typically means a six-night stay with three ceremonies. The maximum stay of two weeks includes up to six ceremonies." },
  { question: "How long does a ceremony last?", answer: "Preparation for ceremony begins at 6pm. Ceremony starts shortly after. Each ceremony runs five to six hours, with the healers and a support team present throughout." },
  { question: "How many ceremonies do you recommend?", answer: "The minimum is three ceremonies. For any deeper, longer-arc work, we strongly recommend five or six." },
  { question: "What is the minimum age?", answer: "Eighteen. Dreamglade does not accept guests under the age of 18." },
  { question: "Is it okay to participate in ceremony during my menstrual cycle?", answer: "Yes, this is a common concern and it is safe. We have had many guests come and join during that time of the month." },
  { question: "How does the application process work?", answer: "The first step is a short inquiry — no medical history. Paul reads every one personally. If it looks like a fit, he writes back to start a conversation. Full registration and a signed agreement come later, by email, before your arrival date is confirmed." },
  { question: "How much does it cost?", answer: "Current pricing is shown in the pricing section of the home page." },
  { question: "What is included in the price?", answer: "Accommodation in a private, two-person, or communal thatched tambo, all meals, ceremonies, plant dieta, breathwork, sauna, and integration support before and after your stay. Group transport from the designated city meeting point in Iquitos on the first day of your retreat and drop-off to the city of Iquitos and Iquitos airport are included for flights after 3 PM. Not included: international and domestic flights, airport pickup on arrival, travel insurance, visas, and vaccinations." },
  { question: "Should I book my flights before my application is confirmed?", answer: "No — we recommend waiting until Paul has reviewed your application and confirmed your dates before you book flights. Once your place is confirmed and your deposit is in, you can book with confidence." },
  { question: "What is the deposit and cancellation policy?", answer: "A 50% deposit confirms your place. Cancellations within seven days get your deposit back minus a $100 cancellation fee. Specifics are confirmed in the Stage 2 registration and agreement." },
  { question: "Is transport included?", answer: "Yes. We pick you up at the designated city meeting point in Iquitos at 1 PM on the first day of your retreat and bring you to the property by 4x4. Drop-off at Iquitos airport is included for departures after 3 PM on the last day. Airport pickup is not included. Uber is available in Iquitos, but it is smart to bring cash in soles in case Uber is not working or a driver asks for cash. Motor taxis from the airport to hotels in Iquitos usually cost about 30–70 soles." },
  { question: "Is there Wi-Fi at Dreamglade?", answer: "There is no Wi-Fi in guest rooms or anywhere at the centre, by design. Electricity is limited and simple, and the retreat is designed for quiet time away from normal digital life. Most guests find the disconnection is part of what makes the week work. Some cellphone carriers have limited service around the retreat. We have a generator that runs once a day; this is the time to charge your devices." },
  { question: "What food is served?", answer: "The retreat dieta is light, low-salt, plant-forward, and built around what grows here. Rice, sweet potatoes, yuca, grains and fresh fruit. Nothing fried, and no added sugars." },
  { question: "What is a plant dieta?", answer: "A plant dieta is not just a food diet. In the Amazonian tradition, it is a quiet period of simplicity, attention, and relationship with a master plant. At Dreamglade, the healers prepare a small tea or plant decoction from the selected master plant, which may be a tree, vine, or shrub, for the guest to drink, and the guest follows a simple retreat rhythm around that work." },
  { question: "Can I choose which master plant dieta I do?", answer: "Dreamglade offers six traditional master plant dietas: Marosa, Ajo Sacha, Bobinsana, Machinga, Clavo Huasca, and Planta de Vida. The specific plant is discussed and selected with Maestro Raúl based on the guest, their preparation, and what is appropriate once they arrive. It is not usually chosen from a menu in advance." },
  { question: "Does Dreamglade follow up after the retreat?", answer: "Yes. Paul reaches out within a month of you leaving to see how the landing has been, and ongoing support by email is available if you want it." },
  { question: "Should I stay in Iquitos after the retreat?", answer: "If you can, yes — one or two nights in Iquitos before flying home is worth it. It gives you a softer re-entry: simple food and time to put words to what happened before the bigger noise of normal life starts again." },
  { question: "Can I come on my own?", answer: "No. All bookings are handled through the website or by email with Paul. You cannot show up and join a retreat without going through the booking process." },
  { question: "Is Dreamglade suitable for women traveling alone?", answer: "Yes. Many guests come on their own, including women traveling solo. Dreamglade is a small retreat with personal screening, continuous staff presence, and a calm, respectful setting designed to help guests feel at ease." },
  { question: "I use cannabis regularly. Can I still attend?", answer: "Yes, but be honest about it on your application. For habitual users — daily use over a long period — we recommend stopping cannabis four to six weeks before the retreat and staying off it for two weeks afterward." },
  { question: "What medications are a concern with ayahuasca?", answer: "Ayahuasca contains naturally occurring MAOIs, which can interact dangerously with certain medications and substances. Medication groups that may be unsafe include antidepressants and anxiety medications such as SSRIs and SNRIs, tricyclic antidepressants, MAOIs, stimulants, sedatives, certain prescription pain medications, heart and blood pressure medications, and blood thinners. Cough, cold, and allergy medications may also be relevant, especially formulas containing DXM or pseudoephedrine. This list is not exhaustive. All current and recent medications, supplements, health history, mental health history, and substance use must be disclosed before confirmation." },
  { question: "Do I need to stop my medication before coming?", answer: "Dreamglade does not advise guests to stop, taper, or change medication. Any medication change — including tapering before a retreat — must be discussed with and supervised by the healthcare professional who prescribed it. Paul reviews disclosures personally, but Dreamglade does not provide medical advice or medical clearance." },
  { question: "Is there a full list of contraindicated medications?", answer: "There is no single complete public list, because individual health situations vary. Guests must disclose all current and recent medications, supplements, health conditions, mental health history, and substance use. Paul reviews disclosures personally and may ask follow-up questions before confirming whether the next step is appropriate." },
  { question: "Who handles my health information?", answer: "Paul, our integration support specialist." },
  { question: "What about cannabis, alcohol, or recreational substances?", answer: "Alcohol, cannabis, recreational drugs, and other substances may affect preparation and safety. Guests are asked to disclose substance use honestly during the intake process so Paul can review the situation and ask follow-up questions if needed." },
  { question: "What does the pre-retreat dieta involve?", answer: "For at least two weeks before arrival, guests are expected to come off processed foods, pork, red meat, alcohol, recreational substances, fermented foods, caffeine and limit salt and sugar. Walks, rest, and hydration are recommended. Most guests find it helpful to spend the last week noting what they are bringing — an intention they can put in writing." },
  { question: "What should I bring?", answer: "We recommend bringing loose, light clothing for ceremony, natural insect repellent, sandals, a refillable water bottle, a notebook, and a flashlight with a red light feature because it is less disruptive for other guests. All toiletries, including soaps and toothpaste, should be natural. Paul will give you more details once you are confirmed." },
  { question: "Are there other activities besides ceremony?", answer: "Yes. Plant baths, plant dietas, breathwork, jungle trails to explore and sauna are included." },
  { question: "What if I get sick during ceremony?", answer: "Purging — vomiting, sometimes diarrhea — is common and is part of the work. Each guest has their own bucket within arm's reach, and the support team is in the room throughout the night. Nothing about it is treated as shameful." },
  { question: "I am worried about being without my phone. Is that a problem?", answer: "It is often one of the bigger adjustments at the start of the retreat, especially in the first couple of days. But most guests find that once they settle in, the quiet becomes part of what they value most. If you need to check in with a family member to let them know you are safe, please let a team member know and we will help make that happen." },
  { question: "When can I arrive at Dreamglade?", answer: "Dreamglade does not run fixed-date group retreats. You can start your stay on a Monday or a Friday. A Wednesday start is sometimes possible under special conditions." },
  { question: "Can I leave the property during my stay?", answer: "No. Once you arrive at Dreamglade, you stay on the land for the full retreat. We do not run day trips out from the centre." },
];
