import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  images: { formats: ["image/webp"] },
  async redirects() {
    return [
      { source: "/about", destination: "/#about", permanent: true },
      { source: "/about/dreamglade", destination: "/#about", permanent: true },
      { source: "/about/location", destination: "/#about", permanent: true },
      { source: "/about/stace", destination: "/#about", permanent: true },
      { source: "/about/ayahuasca-and-amazonian-shamanism", destination: "/what-to-expect", permanent: true },
      { source: "/about/ceremony", destination: "/what-to-expect", permanent: true },
      { source: "/services/accommodation", destination: "/what-to-expect", permanent: true },
      { source: "/services/the-communal-house", destination: "/what-to-expect", permanent: true },
      { source: "/services/retreat-services", destination: "/what-to-expect", permanent: true },
      { source: "/about/sauna-sweat-lodge", destination: "/what-to-expect", permanent: true },
      { source: "/come-prepared", destination: "/safety-preparation", permanent: true },
      { source: "/about/medicinal-plant-dietas", destination: "/safety-preparation", permanent: true },
      { source: "/about/kambo-treatments", destination: "/safety-preparation", permanent: true },
      { source: "/the-dream-team", destination: "/#healers", permanent: true },
      { source: "/the-dream-team/shipibo-healers", destination: "/#healers", permanent: true },
      { source: "/the-dream-team/owners-facilitators-wade-clarisa", destination: "/#about", permanent: true },
      { source: "/the-dream-team/yoga-breathwork-teacher-mair", destination: "/what-to-expect", permanent: true },
      { source: "/the-dream-team/yoga-teacher-chef-britt", destination: "/what-to-expect", permanent: true },
      { source: "/the-dream-team/drew-whelpley-retreat-assistant", destination: "/#about", permanent: true },
      { source: "/services/booking-a-retreat", destination: "/#pricing", permanent: true },
      { source: "/booking-integration-coach-paul", destination: "/apply", permanent: true },
      { source: "/booking-integration-coach-paul-chard", destination: "/apply", permanent: true },
      { source: "/contact", destination: "/apply", permanent: true },
      { source: "/contact-us", destination: "/apply", permanent: true },
      { source: "/testimonials-3/written-testimonials", destination: "/#reviews", permanent: true },
      { source: "/testimonials-3/videos", destination: "/#reviews", permanent: true },
      { source: "/testimonials-3/:path*", destination: "/#reviews", permanent: true },
      { source: "/written-testimonials-2", destination: "/#reviews", permanent: true },
      { source: "/category/testimonials/:path*", destination: "/#reviews", permanent: true },
      { source: "/author/dynafish", destination: "/#reviews", permanent: true },
      { source: "/author/dynafish/:path*", destination: "/#reviews", permanent: true },
      { source: "/sarah-m-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/anna-latvia", destination: "/#reviews", permanent: true },
      { source: "/adam-m-canada", destination: "/#reviews", permanent: true },
      { source: "/adam-p-australia", destination: "/#reviews", permanent: true },
      { source: "/alina-y-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/anna-tony-australia", destination: "/#reviews", permanent: true },
      { source: "/brice-d-ontario-canada", destination: "/#reviews", permanent: true },
      { source: "/charlie-mexico", destination: "/#reviews", permanent: true },
      { source: "/chris-kilham", destination: "/#reviews", permanent: true },
      { source: "/dave-mc-canada", destination: "/#reviews", permanent: true },
      { source: "/dean-h-u-k", destination: "/#reviews", permanent: true },
      { source: "/diana-canada", destination: "/#reviews", permanent: true },
      { source: "/drew-w-texas-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/max-r-london-u-k", destination: "/#reviews", permanent: true },
      { source: "/jimi-lewis-london-u-k", destination: "/#reviews", permanent: true },
      { source: "/hoang-v-california-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/lisa-phoenix-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/gino-p-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/greg-h-new-york-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/jackie-v-california-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/jann-london-u-k", destination: "/#reviews", permanent: true },
      { source: "/jason-g-texas-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/jessica-soames-brighton-u-k", destination: "/#reviews", permanent: true },
      { source: "/juliana-k-finland", destination: "/#reviews", permanent: true },
      { source: "/marketa-czech-republic", destination: "/#reviews", permanent: true },
      { source: "/max-l-italy", destination: "/#reviews", permanent: true },
      { source: "/matthew-e-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/matthew-london-u-k", destination: "/#reviews", permanent: true },
      { source: "/moses-isreal", destination: "/#reviews", permanent: true },
      { source: "/naia-brazil", destination: "/#reviews", permanent: true },
      { source: "/natasha-london-u-k", destination: "/#reviews", permanent: true },
      { source: "/nikolai-t-norway", destination: "/#reviews", permanent: true },
      { source: "/pavel-m-romania", destination: "/#reviews", permanent: true },
      { source: "/rachel-r-new-zealand", destination: "/#reviews", permanent: true },
      { source: "/raymond-hoevenaar-holland", destination: "/#reviews", permanent: true },
      { source: "/robert-b-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/robby-belgium", destination: "/#reviews", permanent: true },
      { source: "/romina-california-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/scott-dl-new-jersey-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/steve-h-london-u-k", destination: "/#reviews", permanent: true },
      { source: "/steve-j-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/steve-t-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/steve-westhoek-amsterdam-holland", destination: "/#reviews", permanent: true },
      { source: "/chad-los-angeles-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/justin-b-michigan-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/tamika-nsw-australia", destination: "/#reviews", permanent: true },
      { source: "/tanya-london-u-k", destination: "/#reviews", permanent: true },
      { source: "/thor-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/tony-h-u-s-a", destination: "/#reviews", permanent: true },
      { source: "/debora-m-dubai", destination: "/#reviews", permanent: true },
      { source: "/elizabeth-s-denver-colorado", destination: "/#reviews", permanent: true },
      { source: "/martin-g-switzerland", destination: "/#reviews", permanent: true },
      { source: "/resources/recommended-reading", destination: "/faq", permanent: true },
      { source: "/resources/films", destination: "/faq", permanent: true },
      { source: "/resources/links", destination: "/faq", permanent: true },
      { source: "/gallery", destination: "/#about", permanent: true },
      { source: "/gallery/:path*", destination: "/#about", permanent: true },
      { source: "/privacy-policy", destination: "/terms-and-conditions", permanent: true },
      { source: "/terms", destination: "/terms-and-conditions", permanent: true },
    ];
  },
};

export default nextConfig;
